[window]
decorations = "None"
padding = { x = 0, y = 0 }

[env]
TERM = "xterm-256color"

[colors.primary]
foreground = "#a9b7c6"
background = "#2b2b2b"

[cursor]
blink_timeout = 0

[cursor.style]
blinking = "Always"

[cursor.vi_mode_style]
blinking = "Always"
