[window]
decorations = "None"
padding = { x = 0, y = 0 }
option_as_alt = "OnlyLeft"

[env]
TERM = "xterm-256color"

[colors]
cursor = { text = "#2b2b2b", cursor = "#a9b7c6" }

[colors.primary]
foreground = "#a9b7c6"
background = "#2b2b2b"

[cursor]
blink_timeout = 0

[cursor.style]
blinking = "Always"

[cursor.vi_mode_style]
blinking = "Always"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 12

[mouse]
hide_when_typing = true
